version: '3.8'
services:
  # Aplicação Python com OpenTelemetry
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - otelcollector
    environment:
      - OTEL_SERVICE_NAME=app-python
      - OTEL_RESOURCE_ATTRIBUTES=service.version=1.0.0, env=dev
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://192.168.100.30:4318
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://192.168.100.30:4318
  
  # OpenTelemetry Collector
  otelcollector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcollector
    volumes:
      - ../../config/collector/otelcol-config.yml:/etc/otel-collector-config.yml
    command:
      - "--config=/etc/otel-collector-config.yml"
      - "--set=service.telemetry.logs.level=DEBUG"
    ports:
      - "4317:4317" # Porta de recebimento de traces gRPC
      - "4318:4318" # Porta de recebimento de métricas http
    depends_on:
      - clickhouse
  
  # Grafana para visualização de métricas, logs e traces
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - clickhouse
    ports:
      - 3000:3000
    volumes:
      - ../../config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../../config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_INSTALL_PLUGINS= grafana-clickhouse-datasource,vertamedia-clickhouse-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS= vertamedia-clickhouse-datasource
  
  # ClickHouse para armazenamento de métricas, logs e traces
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.12.75-alpine
    container_name: clickhouse
    restart: always
    ports:
      - 8123:8123 
      - 9000:9000
    volumes:
      - ../../config/clickhouse/database.sql:/docker-entrypoint-initdb.d/init_schema.sql
    environment:
      - CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS=true

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
