name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ github.base_ref }}/${{ github.event.repository.name }}"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
